"use client";
import { BarChart3, Bell, CalendarDays, ChevronDown, CircleHelp, CreditCard, LayoutDashboard, LogOut, Menu, Settings2, Target, Wallet, X } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const links = [{ label: "Visão geral", icon: LayoutDashboard }, { label: "Transações", icon: Wallet }, { label: "Contas", icon: CreditCard }, { label: "Planejamento", icon: Target }, { label: "Relatórios", icon: BarChart3 }];
export function Sidebar() {
  const [open, setOpen] = useState(false);
  return <><aside className={cn("fixed inset-y-0 left-0 z-40 flex w-64 -translate-x-full flex-col border-r border-sidebar-border bg-sidebar p-5 transition-transform lg:translate-x-0", open && "translate-x-0")}><div className="flex items-center justify-between"><a href="/" className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground font-black">F</span><span className="font-display text-xl font-semibold tracking-tight">finansee<span className="text-primary">.</span></span></a><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setOpen(false)} aria-label="Fechar menu"><X data-icon="inline-start" /></Button></div><div className="mt-9 flex items-center gap-3 rounded-xl border border-sidebar-border bg-sidebar-accent p-3"><div className="grid size-9 place-items-center rounded-full bg-foreground text-background text-xs font-bold">DM</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">Diego Martins</p><p className="text-xs text-muted-foreground">Plano pessoal</p></div><ChevronDown className="size-4 text-muted-foreground" /></div><nav className="mt-8 flex flex-1 flex-col gap-1"><p className="mb-2 px-3 text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground">Menu principal</p>{links.map(({ label, icon: Icon }, index) => <a key={label} href="#" onClick={() => setOpen(false)} className={cn("flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium transition-colors", index === 0 ? "bg-sidebar-accent text-sidebar-foreground" : "text-muted-foreground hover:bg-sidebar-accent hover:text-sidebar-foreground")}><Icon className="size-4" />{label}{index === 3 && <span className="ml-auto rounded-full bg-primary/15 px-2 py-0.5 text-[10px] text-primary">novo</span>}</a>)}<p className="mb-2 mt-8 px-3 text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground">Preferências</p><a href="#" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm text-muted-foreground hover:bg-sidebar-accent hover:text-sidebar-foreground"><CalendarDays className="size-4" />Calendário</a><a href="#" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm text-muted-foreground hover:bg-sidebar-accent hover:text-sidebar-foreground"><Settings2 className="size-4" />Configurações</a></nav><div className="border-t border-sidebar-border pt-4"><a href="#" className="flex items-center gap-3 px-3 py-3 text-sm text-muted-foreground hover:text-foreground"><CircleHelp className="size-4" />Central de ajuda</a><a href="#" className="flex items-center gap-3 px-3 py-3 text-sm text-muted-foreground hover:text-foreground"><LogOut className="size-4" />Sair</a></div></aside><Button variant="outline" size="icon" className="fixed left-4 top-4 z-30 bg-background lg:hidden" onClick={() => setOpen(true)} aria-label="Abrir menu"><Menu data-icon="inline-start" /></Button></>;
}
