import { ArrowDownRight, ArrowUpRight, CircleAlert, CreditCard, Sparkles, Target, TrendingUp, WalletCards } from "@/components/icons";
import Link from "next/link";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Sidebar } from "@/components/dashboard/sidebar";
import { CashflowChart } from "@/components/dashboard/chart";
import { BalanceCard } from "@/components/dashboard/balance-card";
import { EconomicCalendar } from "@/components/ui/economic-calendar";
import { DashboardNavbar } from "@/components/dashboard/dashboard-navbar";
import { MonthSelector } from "@/components/dashboard/month-selector";
import { MetricCard } from "@/components/dashboard/metric-card";
import { TransactionList, type TransactionListItem } from "@/components/ui/transaction-list";
import { getDashboardData, formatBRL } from "@/server/dashboard";
import { demoSpaces, getSpaceDisplayName, resolveSpaceId } from "@/server/space";
import { getTransactionOptions } from "@/server/transactions";
import { GreetingVisual } from "@/components/dashboard/greeting-visual";
import { getBusinessMonth } from "@/lib/business-date";

export default async function Home({ searchParams }: { searchParams: Promise<{ space?: string; month?: string }> }) {
  const params = await searchParams;
  const spaceId = await resolveSpaceId(params.space);
  const currentMonth = getBusinessMonth();
  const month = /^\d{4}-(0[1-9]|1[0-2])$/.test(params.month ?? "") ? params.month! : currentMonth;
  const [data, transactionOptions, displayName] = await Promise.all([getDashboardData(spaceId, month), getTransactionOptions(spaceId), getSpaceDisplayName(spaceId)]);
  const isDemoSpace = demoSpaces.includes(spaceId as (typeof demoSpaces)[number]);
  const combinedData = isDemoSpace ? await getDashboardData("combined-space", month) : data;
  const now = new Date();
  const dateLabel = new Intl.DateTimeFormat("pt-BR", { dateStyle: "full", timeZone: "America/Sao_Paulo" }).format(now);
  const hour = Number(new Intl.DateTimeFormat("pt-BR", { hour: "numeric", hour12: false, timeZone: "America/Sao_Paulo" }).format(now));
  const greeting = hour < 12 ? "Bom dia" : hour < 18 ? "Boa tarde" : "Boa noite";
  return <div className="min-h-screen bg-background"><Sidebar /><DashboardNavbar /><main className="min-h-screen lg:pl-64"><div className="mx-auto max-w-[1500px] px-5 pb-12 pt-20 sm:px-8 lg:px-10 lg:pt-24">
    <header className="relative grid gap-6 border-b border-border pb-7 xl:grid-cols-[0.8fr_1.2fr] xl:items-stretch"><div className="flex flex-col justify-center pr-20 sm:pr-0"><p className="text-sm text-muted-foreground">{dateLabel}</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight sm:text-4xl">{greeting}, {displayName}<GreetingVisual night={hour >= 18 || hour < 6} /></h1><p className="mt-2 max-w-lg text-sm text-muted-foreground">Aqui está o seu panorama financeiro para manter o mês sob controle.</p></div><BalanceCard key={spaceId} balanceCents={data.balance} forecastCents={data.forecast} combinedBalanceCents={combinedData.balance} combinedForecastCents={combinedData.forecast} initialMode={spaceId === "combined-space" ? "combined" : "individual"} allowModeToggle={spaceId !== "combined-space"} spaceId={spaceId} accounts={transactionOptions.accounts} categories={transactionOptions.categories} /></header>
    <EconomicCalendar title="Contas e cartões" accounts={data.accounts.filter((account) => account.type === "credit_card").map((account, index) => ({ id: account.id, name: account.name, type: "Cartão de crédito", debtCents: Math.abs(account.balanceCents), dueDay: account.dueDay, tone: index % 2 === 0 ? "purple" as const : "red" as const, ownerInitials: account.ownerInitials, ownerName: account.ownerName, ownerImage: account.ownerImage }))} fixedBills={data.fixedBills} />
    <div className="mt-8 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-display text-lg font-semibold">Visão de {new Intl.DateTimeFormat("pt-BR", { month: "long" }).format(new Date(`${month}-01T12:00:00`))}</h2><p className="text-sm text-muted-foreground">Acompanhe o que já aconteceu e o que vem pela frente.</p></div><MonthSelector value={month} /></div>
    <section className="mt-5 grid auto-rows-fr grid-cols-2 gap-6 xl:grid-cols-4"><MetricCard label="Saldo total" value={formatBRL(data.balance)} detail="Valor atual" icon={WalletCards} tone="lime" /><MetricCard label="Saldo previsto" value={formatBRL(data.forecast)} detail="Com pendências" icon={TrendingUp} tone="info" /><MetricCard label="Receitas do mês" value={formatBRL(data.income)} detail="Pagas" icon={ArrowUpRight} tone="lime" /><MetricCard label="Despesas do mês" value={formatBRL(data.expenses)} detail="Pagas" icon={ArrowDownRight} tone="warning" /></section>
    <section className="mt-5 grid items-stretch gap-6 xl:grid-cols-[1.5fr_1fr]"><Card><CardHeader className="flex-row items-start justify-between"><div><CardTitle>Fluxo de caixa</CardTitle><CardDescription>Receitas e despesas dos lançamentos do espaço</CardDescription></div><div className="flex gap-4 text-xs text-muted-foreground"><span className="flex items-center gap-2"><span className="size-2 rounded-full bg-[var(--chart-income)]" />Receitas</span><span className="flex items-center gap-2"><span className="size-2 rounded-full bg-[var(--chart-expense)]" />Despesas</span></div></CardHeader><CardContent><CashflowChart data={data.chart} /></CardContent></Card><Card className="bg-sidebar text-sidebar-foreground"><CardHeader><div className="flex items-center justify-between"><CardTitle className="text-sidebar-foreground">Saúde financeira</CardTitle><Sparkles className="size-5 text-primary" /></div><CardDescription className="text-sidebar-foreground/60">Indicador calculado com os dados deste espaço.</CardDescription></CardHeader><CardContent><div className="flex items-center gap-5 py-4"><div className="relative grid size-32 shrink-0 place-items-center rounded-full" style={{ background: `conic-gradient(var(--primary) ${data.health.score}%, var(--health-track) 0)` }}><div className="grid size-24 place-items-center rounded-full bg-sidebar"><span className="font-display text-3xl font-semibold">{data.health.score}</span><span className="-mt-2 text-[10px] text-sidebar-foreground/60">de 100</span></div></div><div><p className="text-sm font-medium">{data.health.score >= 70 ? "Você está no caminho certo" : "Há pontos para acompanhar"}</p><p className="mt-2 text-xs leading-5 text-sidebar-foreground/60">O indicador considera renda, despesas pagas e valores pendentes.</p></div></div><div className="mt-4 grid grid-cols-3 gap-2 border-t border-sidebar-border pt-4 text-center"><div><p className="font-display text-lg font-semibold text-primary">{data.health.economyPercent}%</p><p className="mt-1 text-[10px] text-sidebar-foreground/60">economia</p></div><div><p className="font-display text-lg font-semibold">{data.health.positiveDays}</p><p className="mt-1 text-[10px] text-sidebar-foreground/60">dias positivos</p></div><div><p className="font-display text-lg font-semibold">{data.health.activeGoals}</p><p className="mt-1 text-[10px] text-sidebar-foreground/60">metas ativas</p></div></div></CardContent></Card></section>
    <section className="mt-5 grid items-stretch gap-6 xl:grid-cols-[1.15fr_0.85fr]"><TransactionList wide title="Transações recentes" description="Os últimos movimentos da sua vida financeira" transactions={data.transactions.map(toTransactionListItem)} footerHref={`/transactions?space=${spaceId}`} /><div className="grid items-stretch gap-6 sm:grid-cols-2 xl:grid-cols-1"><TransactionList wide compact title="Contas a pagar" description={`Você tem ${formatBRL(data.pending)} pendentes`} transactions={data.transactions.filter((item) => item.status !== "paid" && item.status !== "cancelled").slice(0, 3).map(toTransactionListItem)} footerHref={`/transactions?space=${spaceId}&status=pending`} /><Card><CardHeader className="flex-row items-start justify-between"><div><CardTitle>Meta em destaque</CardTitle><CardDescription>{data.goal?.name ?? "Nenhuma meta cadastrada"}</CardDescription></div><Target className="size-5 text-primary" /></CardHeader><CardContent>{data.goal ? <><div className="flex items-end justify-between"><span className="font-display text-2xl font-semibold">{Math.min(100, Math.round((data.goal.currentCents / data.goal.targetCents) * 100))}%</span><span className="text-xs text-muted-foreground">{formatBRL(data.goal.currentCents)} de {formatBRL(data.goal.targetCents)}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.min(100, Math.round((data.goal.currentCents / data.goal.targetCents) * 100))}%` }} /></div><p className="mt-3 text-xs text-muted-foreground">Progresso calculado a partir dos valores registrados.</p></> : <p className="py-6 text-sm text-muted-foreground">Cadastre uma meta para acompanhar seu progresso.</p>}</CardContent></Card></div></section>
    {data.alert && <div className="mt-5 flex items-center gap-3 rounded-2xl border border-primary/20 bg-primary/10 px-5 py-4"><CircleAlert className="size-5 shrink-0 text-primary" /><p className="text-sm"><span className="font-semibold">{data.alert.title}.</span> {data.alert.body}</p><Link href={`/accounts?space=${encodeURIComponent(spaceId)}`} className="ml-auto inline-flex min-h-9 shrink-0 items-center justify-center rounded-lg px-3 text-sm font-medium transition-colors hover:bg-primary/15 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">Revisar</Link></div>}<p className="mt-8 text-center text-xs text-muted-foreground">{data.seeded ? "Dados sincronizados com o banco do espaço" : "Conecte o Postgres local e rode npm run db:seed para visualizar seus dados"} · Finansee {new Date().getFullYear()}</p>
  </div></main></div>;
}

function toTransactionListItem(item: { id: string; description: string; category: string; date: string; dueDate?: string | null; amountCents: number; kind: string; account: string; accountType?: string | null; accountImage?: string | null; status?: string }): TransactionListItem {
  const status = item.status ?? "paid";
  const isCard = item.account.toLowerCase().includes("cartão");
  return { id: item.id, name: item.description, type: item.kind === "income" ? `Receita · ${item.category}` : `Despesa · ${item.category}`, amount: item.amountCents / 100, date: item.date, dueDate: item.dueDate, time: status === "paid" ? "Pagamento confirmado" : "Aguardando pagamento", icon: isCard ? <CreditCard className="size-4" /> : <WalletCards className="size-4" />, accountName: item.account, accountType: item.accountType, accountImage: item.accountImage, status: status === "paid" ? "Pago" : "Pendente", paymentMethod: item.account };
}
