import { prisma } from "@/lib/prisma";
import { formatBRL } from "@/lib/utils";
import { requireSpaceAccess } from "@/server/auth-context";
import { getBusinessDate, getBusinessMonth } from "@/lib/business-date";
import { dateOnly } from "@/lib/prisma-utils";
import { getSpaceAlerts } from "@/server/alerts";

export type DashboardData = Awaited<ReturnType<typeof getDashboardData>>;
const emptyDashboard = { balance: 0, forecast: 0, income: 0, expenses: 0, pending: 0, accounts: [], transactions: [], chart: [], fixedBills: [], health: { score: 0, economyPercent: 0, positiveDays: 0, activeGoals: 0 }, goal: null, alert: null, seeded: false };

export async function getDashboardData(spaceId = "personal-space", month = getBusinessMonth()) {
  await requireSpaceAccess(spaceId, "read");
  try {
    const [accounts, rows, goals, alerts] = await Promise.all([prisma.financialAccount.findMany({ where: { financialSpaceId: spaceId, archivedAt: null }, include: { owner: { select: { name: true, image: true } } }, orderBy: { createdAt: "asc" }, take: 20 }), prisma.transaction.findMany({ where: { financialSpaceId: spaceId }, include: { category: { select: { name: true } } }, orderBy: { competenceDate: "desc" } }), prisma.goal.findMany({ where: { financialSpaceId: spaceId }, orderBy: { updatedAt: "desc" }, take: 1 }), getSpaceAlerts(spaceId, month)]);
    if (!accounts.length) return emptyDashboard;
    const monthRows = rows.filter(({ competenceDate, kind, status }) => dateOnly(competenceDate)?.startsWith(month) && kind !== "transfer" && status !== "cancelled");
    const income = monthRows.filter(({ kind, status }) => kind === "income" && status === "paid").reduce((sum, item) => sum + item.amountCents, 0); const expenses = Math.abs(monthRows.filter(({ kind, status }) => kind === "expense" && status === "paid").reduce((sum, item) => sum + item.amountCents, 0)); const pendingExpenses = Math.abs(monthRows.filter(({ kind, status }) => kind === "expense" && status !== "paid" && status !== "cancelled").reduce((sum, item) => sum + item.amountCents, 0)); const pendingIncome = monthRows.filter(({ kind, status }) => kind === "income" && status !== "paid" && status !== "cancelled").reduce((sum, item) => sum + item.amountCents, 0);
    const score = income > 0 ? Math.max(0, Math.min(100, Math.round(100 - (expenses / income) * 70 - (pendingExpenses / income) * 30))) : 0; const positiveDays = new Set(monthRows.filter(({ kind, status }) => kind === "income" && status === "paid").map(({ competenceDate }) => dateOnly(competenceDate))).size; const monthValues = new Map<string, { month: string; income: number; expense: number }>();
    for (const item of rows) { const itemDate = dateOnly(item.competenceDate)!; const chartMonth = new Date(`${itemDate}T12:00:00`).toLocaleDateString("pt-BR", { month: "short" }).replace(".", ""); const current = monthValues.get(chartMonth) ?? { month: chartMonth, income: 0, expense: 0 }; if (item.kind === "income" && item.status !== "cancelled") current.income += Math.max(0, item.amountCents) / 100; if (item.kind === "expense" && item.status !== "cancelled") current.expense += Math.abs(item.amountCents) / 100; monthValues.set(chartMonth, current); }
    const chart = Array.from(monthValues.values()).reverse().slice(-6); const fixedBillGroups = new Map<string, { name: string; values: { label: string; amountCents: number }[] }>();
    for (const item of rows) { if (item.kind !== "expense" || item.status === "cancelled") continue; const account = accounts.find((row) => row.id === item.accountId); const itemDate = dateOnly(item.competenceDate)!; const key = `${item.description}:${item.accountId}`; const current = fixedBillGroups.get(key) ?? { name: `${item.description} · ${account?.name ?? "Conta sem nome"}`, values: [] }; current.values.push({ label: new Intl.DateTimeFormat("pt-BR", { month: "short" }).format(new Date(`${itemDate}T12:00:00`)).replace(".", ""), amountCents: Math.abs(item.amountCents) }); fixedBillGroups.set(key, current); }
    const fixedBills = Array.from(fixedBillGroups.values()).filter((bill) => bill.values.length > 1).map((bill) => ({ ...bill, values: bill.values.slice(-6) })); const featuredGoal = goals[0] ? { name: goals[0].name, currentCents: goals[0].currentCents, targetCents: goals[0].targetCents } : null; const latestAlert = alerts[0] ? { title: alerts[0].title, body: alerts[0].body } : null; const availableBalance = accounts.filter(({ type }) => type !== "credit_card").reduce((sum, item) => sum + item.balanceCents, 0); const todayDay = Number(getBusinessDate().slice(-2)); const daysUntilDue = (day: number | null) => day ? (day - todayDay + 31) % 31 : 32;
    const dashboardAccounts = accounts.map((account) => ({ id: account.id, name: account.name, type: account.type, balanceCents: account.balanceCents, color: account.color, closingDay: account.closingDay, dueDay: account.dueDay, ownerName: account.owner?.name ?? "Responsável", ownerImage: account.owner?.image ?? null, ownerInitials: (account.owner?.name ?? "R").split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase() })).sort((left, right) => { if (left.type !== "credit_card") return right.type === "credit_card" ? -1 : 0; if (right.type !== "credit_card") return 1; return daysUntilDue(left.dueDay) - daysUntilDue(right.dueDay); });
    return { balance: availableBalance, forecast: availableBalance + pendingIncome - pendingExpenses, income, expenses, pending: pendingExpenses, accounts: dashboardAccounts, transactions: monthRows.slice(0, 6).map((item) => { const account = accounts.find((row) => row.id === item.accountId); const itemDate = dateOnly(item.competenceDate)!; return { id: item.id, description: item.description, category: item.category?.name ?? "Sem categoria", date: new Date(`${itemDate}T12:00:00`).toLocaleDateString("pt-BR", { day: "2-digit", month: "short" }).replace(".", ""), dueDate: dateOnly(item.dueDate), amountCents: item.amountCents, kind: item.kind, status: item.status, account: account?.name ?? "Conta principal", accountType: account?.type ?? null, accountImage: account?.type === "credit_card" ? account.owner?.image ?? null : null }; }), chart, fixedBills, health: { score, economyPercent: income ? Math.round(((income - expenses) / income) * 100) : 0, positiveDays, activeGoals: goals.length }, goal: featuredGoal, alert: latestAlert, seeded: true };
  } catch { return emptyDashboard; }
}

export { formatBRL };
