import { prisma } from "@/lib/prisma";
import { requireSpaceAccess } from "@/server/auth-context";
import { dateOnly } from "@/lib/prisma-utils";
import { withRequestLimit } from "@/lib/request-guard";

type BrapiQuote = { symbol?: string; longName?: string; shortName?: string; regularMarketPrice?: number; regularMarketChangePercent?: number; regularMarketTime?: string; logourl?: string };
export type MarketQuote = { symbol: string; name: string; price: number; changePercent: number; observedAt: string; logoUrl: string | null };
export type InvestmentPosition = { id: string; symbol: string; quantityMilli: number; averagePriceCents: number; acquiredAt: string; investedCents: number; currentCents: number | null; resultCents: number | null; resultPercent: number | null };

export async function getInvestmentQuotes(spaceId = "personal-space") {
  await requireSpaceAccess(spaceId, "read"); const storedPositions = await prisma.investmentPosition.findMany({ where: { financialSpaceId: spaceId }, orderBy: { acquiredAt: "desc" } }); const symbols = (process.env.FINANSEE_INVESTMENT_SYMBOLS ?? "PETR4,VALE3,ITUB4").split(",").map((symbol) => symbol.trim().toUpperCase()).filter(Boolean).slice(0, 10);
  if (!symbols.length) return { quotes: [] as MarketQuote[], positions: storedPositions.map((position) => toPosition(position, null)), configured: false, message: "Configure ativos para acompanhar o mercado." };
  try { const response = await withRequestLimit("external:brapi:quotes", () => fetch(`https://brapi.dev/api/v2/stocks/quote?symbols=${encodeURIComponent(symbols.join(","))}`, { headers: process.env.BRAPI_TOKEN ? { Authorization: `Bearer ${process.env.BRAPI_TOKEN}` } : undefined, next: { revalidate: 300 }, signal: AbortSignal.timeout(5_000) }), { limit: 30, windowMs: 60_000, concurrency: 2, timeoutMs: 6_000 }); if (!response.ok) return { quotes: [] as MarketQuote[], positions: storedPositions.map((position) => toPosition(position, null)), configured: false, message: "Não foi possível consultar as cotações agora." }; const payload = await response.json() as { results?: BrapiQuote[] }; const quotes = (payload.results ?? []).flatMap((item) => typeof item.symbol === "string" && typeof item.regularMarketPrice === "number" && Number.isFinite(item.regularMarketPrice) ? [{ symbol: item.symbol, name: item.longName ?? item.shortName ?? item.symbol, price: item.regularMarketPrice, changePercent: typeof item.regularMarketChangePercent === "number" ? item.regularMarketChangePercent : 0, observedAt: item.regularMarketTime ?? new Date().toISOString(), logoUrl: item.logourl ?? null }] : []); return { quotes, positions: storedPositions.map((position) => toPosition(position, quotes.find((quote) => quote.symbol === position.symbol) ?? null)), configured: true, message: quotes.length ? "Cotações atualizadas." : "Nenhuma cotação disponível para os ativos configurados." }; } catch { return { quotes: [] as MarketQuote[], positions: storedPositions.map((position) => toPosition(position, null)), configured: false, message: "O serviço de mercado está indisponível no momento." }; }
}

function toPosition(position: { id: string; symbol: string; quantityMilli: number; averagePriceCents: number; acquiredAt: Date }, quote: MarketQuote | null): InvestmentPosition { const investedCents = Math.round(position.quantityMilli * position.averagePriceCents / 1000); const currentCents = quote ? Math.round(position.quantityMilli * quote.price * 100 / 1000) : null; const resultCents = currentCents === null ? null : currentCents - investedCents; return { id: position.id, symbol: position.symbol, quantityMilli: position.quantityMilli, averagePriceCents: position.averagePriceCents, acquiredAt: dateOnly(position.acquiredAt)!, investedCents, currentCents, resultCents, resultPercent: resultCents === null || investedCents === 0 ? null : (resultCents / investedCents) * 100 }; }
