"use client";

import { useEffect, useState, useTransition } from "react";
import { toast } from "sonner";
import { Banknote, CreditCard, RefreshCw, Trash2, WalletCards } from "@/components/icons";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty";
import { Skeleton } from "@/components/ui/skeleton";
import { formatBRL } from "@/lib/utils";

type OpenFinanceData = Awaited<ReturnType<typeof import("@/server/open-finance").listOpenFinance>>;
type ConnectClient = new (options: { connectToken: string; onSuccess: (item: { itemId?: string; id?: string }) => void; onError?: () => void; onExit?: () => void }) => { init: () => void };
declare global { interface Window { PluggyConnect?: ConnectClient } }

function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "Ainda não sincronizado"; }

export function OpenFinancePage({ spaceId, initialData }: { spaceId: string; initialData: OpenFinanceData }) {
  const [data, setData] = useState(initialData);
  const [pending, startTransition] = useTransition();
  const [loading, setLoading] = useState(false);
  const [widgetReady, setWidgetReady] = useState(false);
  const brlAccounts = data.connections.flatMap((connection) => connection.accounts.filter((account) => account.currencyCode === "BRL"));
  const totalBalance = brlAccounts.reduce((total, account) => total + (account.currentBalanceCents ?? 0), 0);

  useEffect(() => { const script = document.createElement("script"); script.src = "https://cdn.pluggy.ai/pluggy-connect/v2.7.0/pluggy-connect.js"; script.async = true; script.onload = () => setWidgetReady(true); document.head.appendChild(script); return () => script.remove(); }, []);

  async function refresh() { setLoading(true); try { const response = await fetch(`/api/open-finance/connections?spaceId=${encodeURIComponent(spaceId)}`, { cache: "no-store" }); const result = await response.json() as OpenFinanceData & { message?: string }; if (!response.ok) throw new Error(result.message); setData(result); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível atualizar."); } finally { setLoading(false); } }
  async function connect() { setLoading(true); try { const response = await fetch("/api/open-finance/connect-token", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ spaceId }) }); const result = await response.json() as { accessToken?: string; message?: string }; if (!response.ok || !result.accessToken) throw new Error(result.message); if (!window.PluggyConnect) throw new Error("O componente de conexão ainda está carregando."); new window.PluggyConnect({ connectToken: result.accessToken, onSuccess: async (item) => { const itemId = item.itemId ?? item.id; if (!itemId) return toast.error("A instituição não retornou um identificador válido."); const sync = await fetch("/api/open-finance/sync", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ spaceId, itemId }) }); if (!sync.ok) { const body = await sync.json() as { message?: string }; toast.error(body.message); } else { toast.success("Instituição conectada e dados importados."); await refresh(); } setLoading(false); }, onError: () => { toast.error("Não foi possível concluir o consentimento."); setLoading(false); }, onExit: () => setLoading(false) }).init(); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível conectar."); setLoading(false); } }
  function disconnect(connectionId: string) { if (!window.confirm("Remover esta conexão? O histórico já importado será preservado.")) return; startTransition(async () => { const response = await fetch(`/api/open-finance/connections/${connectionId}?spaceId=${encodeURIComponent(spaceId)}`, { method: "DELETE" }); if (!response.ok) toast.error("Não foi possível remover a conexão."); else { toast.success("Conexão removida. O histórico foi preservado."); await refresh(); } }); }

  return <main className="min-h-screen bg-background"><div className="mx-auto max-w-[1240px] px-5 pb-12 pt-20 lg:pl-64 sm:px-8 lg:px-10 lg:pt-24"><header className="flex flex-col gap-5 border-b border-border pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Conexões bancárias</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight sm:text-4xl">Open Finance</h1><p className="mt-2 max-w-xl text-sm text-muted-foreground">Leia saldos e transações das suas instituições em um só lugar, sem permitir movimentações bancárias.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={refresh} disabled={loading || pending}><RefreshCw data-icon />Atualizar dados</Button><Button onClick={connect} disabled={loading || !widgetReady}><CreditCard data-icon />{widgetReady ? "Conectar instituição" : "Carregando conexão..."}</Button></div></header>{loading && <div className="mt-5 grid gap-3" role="status" aria-label="Atualizando dados"><Skeleton className="h-4 w-48" /><Skeleton className="h-20 w-full" /></div>}
    <section className="mt-7 grid gap-5 sm:grid-cols-2"><Card className="border-primary/20 bg-primary/5"><CardHeader><CardDescription>Saldo consolidado em BRL</CardDescription><CardTitle className="font-display text-3xl">{formatBRL(totalBalance)}</CardTitle></CardHeader><CardContent><p className="text-xs text-muted-foreground">Somente contas importadas em reais. Outras moedas aparecem separadamente.</p></CardContent></Card><Card><CardHeader><CardDescription>Instituições conectadas</CardDescription><CardTitle className="font-display text-3xl">{data.connections.length}</CardTitle></CardHeader><CardContent><p className="text-xs text-muted-foreground">Os dados são somente leitura e podem ser atualizados manualmente.</p></CardContent></Card></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]"><Card><CardHeader><CardTitle>Instituições</CardTitle><CardDescription>Consentimentos e status das conexões.</CardDescription></CardHeader><CardContent className="grid gap-3">{data.connections.length ? data.connections.map((connection) => <article key={connection.id} className="rounded-xl border border-border p-4"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3">{connection.logoUrl ? <span role="img" aria-label={`Logo de ${connection.name}`} className="size-10 shrink-0 rounded-lg bg-contain bg-center bg-no-repeat" style={{ backgroundImage: `url(${connection.logoUrl})` }} /> : <span className="grid size-10 place-items-center rounded-lg bg-muted"><Banknote /></span>}<div className="min-w-0"><p className="truncate text-sm font-semibold">{connection.name}</p><p className="text-xs text-muted-foreground">Atualizado em {formatDate(connection.lastSyncedAt)}</p></div></div><Badge variant={connection.status === "ACTIVE" ? "secondary" : "destructive"}>{connection.status === "ACTIVE" ? "Ativa" : "Atenção"}</Badge></div>{connection.errorMessage && <p className="mt-3 text-xs text-destructive">{connection.errorMessage}</p>}<div className="mt-3 flex justify-end"><Button variant="ghost" size="sm" onClick={() => disconnect(connection.id)} disabled={pending}><Trash2 data-icon />Remover conexão</Button></div></article>) : <Empty className="border border-dashed"><EmptyHeader><EmptyMedia variant="icon"><Banknote /></EmptyMedia><EmptyTitle>Nenhuma instituição conectada</EmptyTitle><EmptyDescription>Conecte seu banco para importar contas e transações em modo somente leitura.</EmptyDescription></EmptyHeader><EmptyContent><Button onClick={connect} disabled={loading || !widgetReady}>Conectar instituição</Button></EmptyContent></Empty>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Contas importadas</CardTitle><CardDescription>As contas ficam vinculadas às contas internas, sem duplicação.</CardDescription></CardHeader><CardContent className="grid gap-3">{data.connections.flatMap((connection) => connection.accounts.map((account) => <div key={account.id} className="flex items-center justify-between gap-4 rounded-xl border border-border p-4"><div className="flex min-w-0 items-center gap-3"><WalletCards className="size-5 shrink-0 text-primary" /><div className="min-w-0"><p className="truncate text-sm font-semibold">{account.name}</p><p className="text-xs text-muted-foreground">{account.maskedNumber ?? "Número não informado"} · {account.currencyCode}</p></div></div><p className="shrink-0 text-sm font-semibold">{account.currencyCode === "BRL" ? formatBRL(account.currentBalanceCents ?? 0) : `${(account.currentBalanceCents ?? 0) / 100} ${account.currencyCode}`}</p></div>))}{!brlAccounts.length && !data.connections.length && <p className="py-8 text-center text-sm text-muted-foreground">As contas aparecerão após a primeira sincronização.</p>}</CardContent></Card></section>
    <Card className="mt-5"><CardHeader><CardTitle>Transações recentes</CardTitle><CardDescription>Importadas da instituição, ordenadas da mais recente para a mais antiga.</CardDescription></CardHeader><CardContent>{data.transactions.length ? <div className="grid gap-2">{data.transactions.map((transaction) => <div key={transaction.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border p-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{transaction.merchantName ?? transaction.description}</p><p className="text-xs text-muted-foreground">{transaction.accountName} · {new Intl.DateTimeFormat("pt-BR").format(new Date(transaction.date))}</p></div><p className={transaction.amountCents < 0 ? "text-sm font-semibold text-destructive" : "text-sm font-semibold text-primary"}>{formatBRL(transaction.amountCents)}</p></div>)}</div> : <p className="py-8 text-center text-sm text-muted-foreground">Nenhuma transação importada ainda.</p>}</CardContent></Card>
  </div></main>;
}
