import { relations } from "drizzle-orm";
import { boolean, date, integer, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

const id = () => text("id").primaryKey();
const timestamps = { createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() };

export const user = pgTable("user", {
  id: id(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("email_verified").default(false).notNull(), image: text("image"), ...timestamps,
});
export const session = pgTable("session", { id: id(), expiresAt: timestamp("expires_at").notNull(), token: text("token").notNull().unique(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(), ipAddress: text("ip_address"), userAgent: text("user_agent"), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }) });
export const account = pgTable("account", { id: id(), accountId: text("account_id").notNull(), providerId: text("provider_id").notNull(), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }), accessToken: text("access_token"), refreshToken: text("refresh_token"), idToken: text("id_token"), accessTokenExpiresAt: timestamp("access_token_expires_at"), refreshTokenExpiresAt: timestamp("refresh_token_expires_at"), scope: text("scope"), password: text("password"), ...timestamps });
export const verification = pgTable("verification", { id: id(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expires_at").notNull(), ...timestamps });

export const financialSpace = pgTable("financial_space", { id: id(), name: text("name").notNull(), ownerId: text("owner_id").notNull().references(() => user.id), ...timestamps });
export const spaceMember = pgTable("space_member", { id: id(), financialSpaceId: text("financial_space_id").notNull().references(() => financialSpace.id, { onDelete: "cascade" }), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }), role: text("role").notNull().default("owner"), ...timestamps }, (table) => ({ memberUnique: uniqueIndex("space_member_unique").on(table.financialSpaceId, table.userId) }));
export const financialAccount = pgTable("financial_account", { id: id(), financialSpaceId: text("financial_space_id").notNull().references(() => financialSpace.id, { onDelete: "cascade" }), name: text("name").notNull(), type: text("type").notNull().default("checking"), balanceCents: integer("balance_cents").notNull().default(0), color: text("color").notNull().default("lime"), ...timestamps });
export const category = pgTable("category", { id: id(), financialSpaceId: text("financial_space_id").notNull().references(() => financialSpace.id, { onDelete: "cascade" }), name: text("name").notNull(), kind: text("kind").notNull().default("expense"), color: text("color").notNull().default("lime"), ...timestamps });
export const transaction = pgTable("transaction", { id: id(), financialSpaceId: text("financial_space_id").notNull().references(() => financialSpace.id, { onDelete: "cascade" }), accountId: text("account_id").notNull().references(() => financialAccount.id), categoryId: text("category_id").references(() => category.id), description: text("description").notNull(), amountCents: integer("amount_cents").notNull(), kind: text("kind").notNull(), status: text("status").notNull().default("paid"), competenceDate: date("competence_date").notNull(), dueDate: date("due_date"), paidAt: timestamp("paid_at"), ...timestamps });
export const budget = pgTable("budget", { id: id(), financialSpaceId: text("financial_space_id").notNull().references(() => financialSpace.id, { onDelete: "cascade" }), categoryId: text("category_id").notNull().references(() => category.id), month: date("month").notNull(), limitCents: integer("limit_cents").notNull(), ...timestamps });
export const goal = pgTable("goal", { id: id(), financialSpaceId: text("financial_space_id").notNull().references(() => financialSpace.id, { onDelete: "cascade" }), name: text("name").notNull(), targetCents: integer("target_cents").notNull(), currentCents: integer("current_cents").notNull().default(0), dueDate: date("due_date"), ...timestamps });
export const alert = pgTable("alert", { id: id(), financialSpaceId: text("financial_space_id").notNull().references(() => financialSpace.id, { onDelete: "cascade" }), title: text("title").notNull(), body: text("body").notNull(), severity: text("severity").notNull().default("info"), readAt: timestamp("read_at"), ...timestamps });

export const spaceRelations = relations(financialSpace, ({ many }) => ({ members: many(spaceMember), accounts: many(financialAccount), transactions: many(transaction) }));
export const accountRelations = relations(financialAccount, ({ many }) => ({ transactions: many(transaction) }));
export const categoryRelations = relations(category, ({ many }) => ({ transactions: many(transaction), budgets: many(budget) }));
export const transactionRelations = relations(transaction, ({ one }) => ({ account: one(financialAccount, { fields: [transaction.accountId], references: [financialAccount.id] }), category: one(category, { fields: [transaction.categoryId], references: [category.id] }) }));
