"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { ArrowUpRight, Target } from "@/components/icons";

export default function LoginPage() {
  const [mode, setMode] = useState<"sign-in" | "sign-up">("sign-in");
  const [message, setMessage] = useState("");
  const router = useRouter();
  async function submit(formData: FormData) { setMessage(""); const endpoint = mode === "sign-in" ? "sign-in" : "sign-up"; const response = await fetch(`/api/auth/${endpoint}/email`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: formData.get("name"), email: formData.get("email"), password: formData.get("password") }) }); if (response.ok) router.push("/"); else setMessage("Não foi possível concluir. Confira os dados e tente novamente."); }
  return <main className="grid min-h-screen place-items-center bg-sidebar px-5 py-10 text-sidebar-foreground"><div className="w-full max-w-md"><Link href="/" className="mx-auto flex w-fit items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground font-black">F</span><span className="font-display text-2xl font-semibold">finansee<span className="text-primary">.</span></span></Link><div className="mt-10 rounded-3xl border border-sidebar-border bg-sidebar-accent p-7 shadow-2xl"><div className="grid size-11 place-items-center rounded-2xl bg-primary/15 text-primary"><Target /></div><h1 className="mt-6 font-display text-2xl font-semibold">Seu dinheiro, com clareza.</h1><p className="mt-2 text-sm text-sidebar-foreground/60">Entre para acessar seu panorama financeiro.</p><form action={submit} className="mt-7 flex flex-col gap-4">{mode === "sign-up" && <input name="name" required placeholder="Seu nome" className="h-12 rounded-xl border border-sidebar-border bg-sidebar px-4 text-sm outline-none placeholder:text-sidebar-foreground/40 focus:border-primary" />}<input name="email" type="email" required placeholder="seu@email.com" className="h-12 rounded-xl border border-sidebar-border bg-sidebar px-4 text-sm outline-none placeholder:text-sidebar-foreground/40 focus:border-primary" /><input name="password" type="password" required minLength={8} placeholder="Senha (mínimo 8 caracteres)" className="h-12 rounded-xl border border-sidebar-border bg-sidebar px-4 text-sm outline-none placeholder:text-sidebar-foreground/40 focus:border-primary" /><button className="flex h-12 items-center justify-center gap-2 rounded-xl bg-primary font-semibold text-primary-foreground">{mode === "sign-in" ? "Entrar no Finansee" : "Criar meu espaço"}<ArrowUpRight /></button></form>{message && <p className="mt-4 text-sm text-red-300">{message}</p>}<button onClick={() => setMode(mode === "sign-in" ? "sign-up" : "sign-in")} className="mt-6 w-full text-center text-sm text-sidebar-foreground/60 hover:text-primary">{mode === "sign-in" ? "Ainda não tenho uma conta" : "Já tenho uma conta"}</button></div></div></main>;
}
