import { ArrowUpRight, BarChart3, CircleCheck, Wallet } from "@/components/icons";
import { Card, CardContent } from "@/components/ui/card";
import type { InvestmentPosition, MarketQuote } from "@/server/investments";
import { InvestmentMarketplace } from "@/components/investments/investment-marketplace";
import { InvestmentProjection } from "@/components/investments/investment-projection";
import { InvestmentPortfolio } from "@/components/investments/investment-portfolio";
import { formatBRL } from "@/lib/utils";

export function InvestmentsPage({ spaceId, quotes, positions, message }: { spaceId: string; quotes: MarketQuote[]; positions: InvestmentPosition[]; message: string }) {
  const investedCents = positions.reduce((total, position) => total + position.investedCents, 0);
  const currentCents = positions.reduce((total, position) => total + (position.currentCents ?? position.investedCents), 0);
  const resultCents = currentCents - investedCents;
  return <main className="min-h-screen bg-background lg:pl-64"><div className="mx-auto max-w-[1240px] px-5 pb-12 pt-20 sm:px-8 lg:px-10 lg:pt-24"><header className="border-b border-border pb-7"><p className="text-sm font-medium text-primary">Seu dinheiro trabalhando</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight sm:text-4xl">Investimentos</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Encontre uma opção que combina com você, escolha quanto aplicar e acompanhe tudo em um só lugar.</p></header><section className="mt-6 grid gap-3 sm:grid-cols-3"><SummaryCard icon={Wallet} label="Total investido" value={formatBRL(investedCents)} detail={positions.length ? `${positions.length} aplicação${positions.length === 1 ? "" : "ões"}` : "Comece sua primeira aplicação"} /><SummaryCard icon={BarChart3} label="Valor acompanhado" value={formatBRL(currentCents)} detail="Com base nas cotações disponíveis" /><SummaryCard icon={ArrowUpRight} label="Resultado estimado" value={`${resultCents >= 0 ? "+" : "−"}${formatBRL(Math.abs(resultCents))}`} detail="Variação da carteira registrada" tone={resultCents >= 0 ? "success" : "danger"} /></section><InvestmentMarketplace spaceId={spaceId} quotes={quotes} /><section className="mt-6 grid gap-4 rounded-2xl border border-primary/15 bg-primary/5 p-4 sm:grid-cols-[auto_1fr] sm:items-center sm:p-5"><span className="grid size-11 place-items-center rounded-xl bg-primary/15 text-primary"><CircleCheck /></span><div><p className="font-semibold">Escolhas simples, decisões conscientes</p><p className="mt-1 text-sm leading-5 text-muted-foreground">As opções são apresentadas para facilitar seu planejamento. Rentabilidade passada não garante resultados futuros e esta tela não é recomendação financeira.</p></div></section><InvestmentProjection initialCents={currentCents} /><InvestmentPortfolio positions={positions} /><p className="mt-6 text-xs text-muted-foreground">{quotes.length ? "Cotações de mercado atualizadas pelo backend do Finansee." : message || "Cotações indisponíveis no momento; suas aplicações continuam salvas."}</p></div></main>;
}

function SummaryCard({ icon: Icon, label, value, detail, tone = "default" }: { icon: typeof Wallet; label: string; value: string; detail: string; tone?: "default" | "success" | "danger" }) { return <Card><CardContent className="p-4 sm:p-5"><div className="flex items-center gap-3"><span className={`grid size-9 place-items-center rounded-xl ${tone === "success" ? "bg-status-success/15 text-status-success" : tone === "danger" ? "bg-status-danger/15 text-status-danger" : "bg-primary/12 text-primary"}`}><Icon className="size-4" /></span><span className="text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">{label}</span></div><p className="mt-4 font-display text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></CardContent></Card>; }
