"use client";

import { Check, Sparkles } from "@/components/icons";
import { useTheme } from "@/components/theme/theme-provider";

export function ThemeSelector() {
  const { theme, mode, setTheme, setMode, options } = useTheme();
  return <section aria-labelledby="theme-selector-title" className="rounded-2xl border border-border bg-card p-5">
    <div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/15 text-primary" aria-hidden="true"><Sparkles className="size-5" /></span><div><h2 id="theme-selector-title" className="font-display text-lg font-semibold">Aparência</h2><p className="mt-1 text-sm leading-5 text-muted-foreground">Escolha uma combinação de cores para deixar o Finansee com a sua cara.</p></div></div>
    <div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{options.map((option) => { const selected = theme === option.id; return <button key={option.id} type="button" aria-pressed={selected} onClick={() => setTheme(option.id)} className="group flex min-h-20 items-center gap-3 rounded-xl border border-border bg-background p-3 text-left transition-[border-color,background-color,transform] hover:-translate-y-0.5 hover:border-primary/60 hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="flex size-10 shrink-0 overflow-hidden rounded-xl border border-border shadow-sm" aria-hidden="true"><span className="h-full w-1/2" style={{ backgroundColor: option.swatches[0] }} /><span className="h-full w-1/2" style={{ backgroundColor: option.swatches[1] }} /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{option.label}</span><span className="mt-0.5 block truncate text-xs text-muted-foreground">{option.description}</span></span><span className={`grid size-5 shrink-0 place-items-center rounded-full border ${selected ? "border-primary bg-primary text-primary-foreground" : "border-border text-transparent"}`} aria-hidden="true"><Check className="size-3" strokeWidth={3} /></span></button>; })}</div>
    <div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-background p-3"><span className="text-sm font-medium">Modo de contraste</span><div className="flex gap-2"><button type="button" aria-pressed={mode === "light"} onClick={() => setMode("light")} className={`rounded-lg px-3 py-2 text-xs font-semibold transition-colors ${mode === "light" ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground hover:bg-accent"}`}>Claro</button><button type="button" aria-pressed={mode === "dark"} onClick={() => setMode("dark")} className={`rounded-lg px-3 py-2 text-xs font-semibold transition-colors ${mode === "dark" ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground hover:bg-accent"}`}>Escuro</button></div></div><p className="mt-4 text-xs text-muted-foreground">A paleta e o modo ficam salvos neste navegador e podem ser combinados livremente.</p>
  </section>;
}
