"use client";

import { useState, useTransition } from "react";
import { Archive, ArrowRightLeft, Plus, Settings2 } from "@/components/icons";
import { AccountForm, type AccountRecord, type AccountType } from "@/components/accounts/account-form";
import { AccountSelect } from "@/components/accounts/account-select";
import { BankMark } from "@/components/accounts/bank-mark";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { CurrencyInput } from "@/components/ui/currency-input";
import { Label } from "@/components/ui/label";
import { addBalance, archiveAccount, createAccount, transferBetweenAccounts, updateAccount } from "@/server/actions/accounts";
import { formatBRL } from "@/lib/utils";
import { parseAmountCents } from "@/lib/finance-rules";

const typeNames: Record<string, string> = { checking: "Débito", credit_card: "Crédito", savings: "Poupança", cash: "Dinheiro" };
const cardColors: Record<string, string> = { lime: "#b8f34b", violet: "#8d72e8", ocean: "#3e9ee8", coral: "#e87968", ink: "#242a27" };

export function AccountsPage({ initialAccounts, spaceId = "personal-space" }: { initialAccounts: AccountRecord[]; spaceId?: string }) {
  const [accounts, setAccounts] = useState(initialAccounts);
  const [editing, setEditing] = useState<string | null>(null);
  const [fromId, setFromId] = useState(initialAccounts[0]?.id ?? "");
  const [toId, setToId] = useState(initialAccounts[1]?.id ?? "");
  const [balanceAccountId, setBalanceAccountId] = useState(initialAccounts[0]?.id ?? "");
  const [pending, startTransition] = useTransition();
  const [message, setMessage] = useState("");
  const hasAccounts = accounts.length > 0;
  const canTransfer = accounts.length >= 2;

  function run(action: () => Promise<{ success: boolean; message?: string }>, onSuccess?: () => void) { startTransition(async () => { const result = await action(); setMessage(result.message ?? ""); if (result.success) onSuccess?.(); }); }
  function save(event: React.FormEvent<HTMLFormElement>, type: AccountType, color: string, id?: string) { event.preventDefault(); const data = new FormData(event.currentTarget); data.set("type", type); data.set("color", color); data.set("spaceId", spaceId); run(() => id ? updateAccount(id, data) : createAccount(data), () => { const balance = parseAmountCents(String(data.get("balance") ?? "0"), { allowZero: true }); const name = String(data.get("name") ?? "Conta"); const bank = String(data.get("bank") ?? "Outro"); const closingDay = type === "credit_card" ? Number(data.get("closingDay")) : null; const dueDay = type === "credit_card" ? Number(data.get("dueDay")) : null; if (id) setAccounts((current) => current.map((item) => item.id === id ? { ...item, name, bank, type, color, balanceCents: balance, closingDay, dueDay, updatedAt: new Date() } : item)); else setAccounts((current) => [...current, { id: `local-${Date.now()}`, name, bank, type, color, balanceCents: balance, closingDay, dueDay, financialSpaceId: spaceId, createdAt: new Date(), updatedAt: new Date() }]); setEditing(null); }); }
  function addAccountBalance(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); data.set("accountId", balanceAccountId); data.set("spaceId", spaceId); run(() => addBalance(data), () => { const cents = parseAmountCents(String(data.get("amount") ?? "")); setAccounts((current) => current.map((account) => account.id === balanceAccountId ? { ...account, balanceCents: account.balanceCents + cents } : account)); event.currentTarget.reset(); }); }
  function transfer(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); data.set("fromId", fromId); data.set("toId", toId); data.set("spaceId", spaceId); run(() => transferBetweenAccounts(data)); }

  return <main className="min-h-screen bg-background lg:pl-64"><div className="mx-auto max-w-[1240px] px-5 pb-12 pt-20 sm:px-8 lg:px-10 lg:pt-24"><header className="flex flex-col gap-5 border-b border-border pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Patrimônio</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight sm:text-4xl">Contas e cartões</h1><p className="mt-2 max-w-xl text-sm text-muted-foreground">Uma visão clara de onde seu dinheiro está — e como ele se movimenta.</p></div><Button onClick={() => setEditing("new")}><Plus data-icon />Nova conta</Button></header>{message && <p className="mt-4 rounded-xl border border-primary/30 bg-primary/10 px-4 py-3 text-sm" role="status">{message}</p>}
    <div className="mt-7 grid gap-6 lg:grid-cols-[minmax(0,1.2fr)_minmax(350px,.8fr)]"><section><Card className="overflow-hidden"><CardHeader className="border-b border-border bg-card/70"><CardTitle>Seus meios de pagamento</CardTitle><CardDescription>{accounts.length ? `${accounts.length} ${accounts.length === 1 ? "conta ativa" : "contas ativas"}` : "Comece adicionando sua primeira conta"}</CardDescription></CardHeader><CardContent className="p-4 sm:p-6">{hasAccounts ? <div className="grid gap-4 sm:grid-cols-2">{accounts.map((account) => <AccountCard key={account.id} account={account} pending={pending} onEdit={() => setEditing(account.id)} onArchive={() => run(() => archiveAccount(account.id, spaceId), () => setAccounts((current) => current.filter((item) => item.id !== account.id)))} />)}</div> : <div className="grid min-h-72 place-items-center rounded-2xl border border-dashed border-border bg-muted/20 p-8 text-center"><div><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-primary/15 text-primary"><Plus /></span><h2 className="mt-4 font-semibold">Seu painel começa aqui</h2><p className="mt-2 max-w-xs text-sm text-muted-foreground">Cadastre uma conta corrente, cartão ou reserva para acompanhar seu patrimônio.</p><Button className="mt-5" onClick={() => setEditing("new")}>Adicionar primeira conta</Button></div></div>}</CardContent></Card></section>
      <aside className="grid content-start gap-5">{editing ? <Card className="border-primary/30 shadow-[0_12px_40px_color-mix(in_srgb,var(--foreground)_8%,transparent)]"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>{editing === "new" ? "Nova conta" : "Editar conta"}</CardTitle><CardDescription className="mt-1">Personalize o cartão e salve os dados com segurança.</CardDescription></div><button type="button" aria-label="Fechar editor" onClick={() => setEditing(null)} className="rounded-lg p-2 text-muted-foreground hover:bg-muted hover:text-foreground">×</button></div></CardHeader><CardContent><AccountForm account={editing === "new" ? undefined : accounts.find((item) => item.id === editing)} pending={pending} onSubmit={(event, type, color) => save(event, type, color, editing === "new" ? undefined : editing)} onCancel={() => setEditing(null)} /></CardContent></Card> : <Card className="border-primary/20 bg-gradient-to-br from-card to-primary/5"><CardHeader><CardTitle className="flex items-center gap-2"><Settings2 className="size-4 text-primary" />Cadastro rápido</CardTitle><CardDescription>Crie um cartão visualmente organizado em poucos passos.</CardDescription></CardHeader><CardContent><Button variant="outline" className="w-full" onClick={() => setEditing("new")}><Plus data-icon />Cadastrar uma conta</Button></CardContent></Card>}
        {hasAccounts && <Card><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="size-4 text-primary" />Adicionar saldo</CardTitle><CardDescription>Registre uma entrada na conta selecionada.</CardDescription></CardHeader><CardContent><form className="grid gap-4" onSubmit={addAccountBalance}><AccountSelect label="Conta" value={balanceAccountId} options={accounts} onChange={setBalanceAccountId} /><label className="grid gap-2"><Label htmlFor="balance-amount">Valor (R$)</Label><CurrencyInput id="balance-amount" name="amount" required className="h-12 rounded-xl" /></label><Button type="submit" disabled={pending} className="w-full">{pending ? "Adicionando..." : "Adicionar saldo"}</Button></form></CardContent></Card>}
        {canTransfer && <Card><CardHeader><CardTitle className="flex items-center gap-2"><ArrowRightLeft className="size-4 text-primary" />Transferir entre contas</CardTitle><CardDescription>Movimente valores entre duas contas do espaço.</CardDescription></CardHeader><CardContent><form className="grid gap-4" onSubmit={transfer}><AccountSelect label="Origem" value={fromId} options={accounts} onChange={setFromId} /><AccountSelect label="Destino" value={toId} options={accounts} onChange={setToId} /><label className="grid gap-2"><Label htmlFor="transfer-amount">Valor (R$)</Label><CurrencyInput id="transfer-amount" name="amount" required className="h-12 rounded-xl" /></label><Button type="submit" disabled={pending} className="w-full">{pending ? "Transferindo..." : "Transferir"}</Button></form></CardContent></Card>}
      </aside></div></div></main>;
}

function AccountCard({ account, onEdit, onArchive, pending }: { account: AccountRecord; onEdit: () => void; onArchive: () => void; pending: boolean }) { const accent = cardColors[account.color] ?? cardColors.lime; return <article className="group relative overflow-hidden rounded-[1.25rem] border border-border bg-card p-4 transition-all hover:-translate-y-0.5 hover:border-primary/50 hover:shadow-lg"><div className="absolute inset-x-0 top-0 h-1" style={{ backgroundColor: accent }} /><div className="flex items-start justify-between gap-3"><BankMark name={account.bank || account.name} type={account.type} /><span className="rounded-full bg-muted px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{typeNames[account.type] ?? "Conta"}</span></div><p className="mt-5 truncate text-sm font-semibold">{account.name}</p><p className="mt-1 text-2xl font-semibold tracking-tight">{formatBRL(account.balanceCents)}</p>{account.type === "credit_card" && <p className="mt-2 text-xs text-muted-foreground">Fecha dia {account.closingDay ?? "--"} · vence dia {account.dueDay ?? "--"}</p>}<div className="mt-5 flex gap-2 border-t border-border pt-3"><Button type="button" variant="outline" size="sm" onClick={onEdit} className="flex-1">Editar</Button><Button type="button" variant="ghost" size="sm" onClick={onArchive} disabled={pending}><Archive data-icon />Arquivar</Button></div></article>; }
